os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
# Download dependencies and build project
  - cd build_conan
  - conan install ..
# Call your build system
  - cmake .. -G "Unix Makefiles"
  - cmake --build ..
