os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
before_install:
  - sudo apt-get install -y libssl-dev libasound2-dev:amd64 libpulse-dev:amd64 mesa-common-dev:amd64 libegl1-mesa-dev:amd64 libgbm-dev:amd64 libjack-dev:amd64 libaudio-dev:amd64 libxcursor-dev:amd64 libxinerama-dev:amd64 libxi-dev:amd64 libxrandr-dev:amd64 libtool-bin
addons:
  apt:
    update: true
install:
# Install conan
  - pip install conan
  - conan user
  - conan config install conan_config/
script:
  - cd build_conan
  - conan install .. --build=missing
# Call your build system
  - cmake .. -G "Unix Makefiles"
  - cmake --build ..
