os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
# Install conan
  - pip install conan
  - conan user
  - conan config install conan_config/
script:
  - cd build_conan
  - conan install ..
# Call your build system
  - cmake .. -G "Unix Makefiles"
  - cmake --build ..
